// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package mysqlquery

import (
	"context"
)

const getUserByName = `-- name: GetUserByName :one
SELECT id, name, created_at FROM users
WHERE name = ? LIMIT 1
`

func (q *Queries) GetUserByName(ctx context.Context, name string) (*User, error) {
	row := q.db.QueryRowContext(ctx, getUserByName, name)
	var i User
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return &i, err
}
